/* auto generated by build:lib*/
import ElementMaker from './ElementMaker';
import FormDialogMaker from './FormDialogMaker';
import FormMaker from './FormMaker';
import TableSearchMaker from './TableSearchMaker';

const version = '0.0.2';
const components = [ElementMaker,FormDialogMaker,FormMaker,TableSearchMaker];
export {
  version,
  ElementMaker,
  FormDialogMaker,
  FormMaker,
  TableSearchMaker
};

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version,
  install,
  ElementMaker,
  FormDialogMaker,
  FormMaker,
  TableSearchMaker
};
